name: Build images

on:
  push:
    branches:
      - main

jobs:
  build-miner-image:
    name: Build Miner Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: build/miner/Dockerfile
          platforms: linux/amd64
          tags: |
            ghcr.io/wizedkyle/artifactsmmo/miner:latest
            ghcr.io/wizedkyle/artifactsmmo/miner:1.0.${{ github.run_id }}