name: Build images

on:
  push:
    branches:
      - main

jobs:
  build-miner-image:
    name: Build Miner Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: "wizedkyle.azurecr.io"
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: build/miner/Dockerfile
          platforms: linux/amd64
          tags:
            wizedkyle.azurecr.io/miner:latest
            wizedkyle.azurecr.io/miner:1.0.${{ github.run_id }}